# Prefiltering grid search - J genes

In [3]:
%load_ext autoreload
%autoreload 2

In [4]:
from utils import *
from pathlib import Path
import pandas as pd

In [5]:
RESULTS_PATH = Path("/home/bartosz/Documents/riot/results/")

In [6]:
ngs_skbio = pd.read_csv("data/skbio_stratified_ngs_alignment_j.csv", index_col=0)
print(f"Number of sequences with evalue more than 0.001: {ngs_skbio[ngs_skbio['e_value'] > 0.001].shape[0]} / {ngs_skbio.shape[0]}")
ngs_skbio = ngs_skbio[ngs_skbio["e_value"] < 0.001]
ground_truth_df = ngs_skbio[["target_id"]]

Number of sequences with evalue more than 0.001: 5242 / 454851

## Top 5 genes

In [5]:
top_n = 5
PARAMS = ["top", "kmer_size", "distance_threshold", "modulo"]

### IGH

In [6]:
results_dir = RESULTS_PATH / "skbio_stratified_ngs_alignment_grid_search_j_igh"
res_df = aggregate_grid_search_results(results_dir, PARAMS, top_n, ground_truth_df, with_rev_comp=False)
res_path = f"results/prefiltering_grid_search_top_{top_n}_no_trash_alignments_fixed_diagonal_stratified_ngs_j_igh.csv"
res_df.to_csv(res_path)
res_df.sort_values("match_percent", ascending=False).head(20)

100%|██████████| 315/315 [08:00<00:00,  1.52s/it]

     top  kmer_size  distance_threshold  modulo  match_percent
173    5          7                  19       1       0.988949
189    5          7                  13       1       0.988769
160    5          7                  17       1       0.988735
243    5          7                  15       1       0.988672
238    5          5                   3       2       0.988480
80     5          7                  11       1       0.988377
44     5          7                   9       1       0.988311
32     5          5                   3       4       0.987441
141    5          5                   5       2       0.987291
78     5          5                   5       4       0.987161
242    5          5                   3       1       0.986932
284    5          5                   3       3       0.986559
82     5          7                   7       1       0.986433
131    5          7                   5       1       0.986330
249    5          7                   3       1       0.986162
292    5          5                   5       3       0.986098
8      5          7                  19       2       0.985861
72     5          7                  17       2       0.985590
258    5          7                  15       2       0.985514
93     5          7                  13       2       0.985108

### IGL

In [13]:
results_dir = RESULTS_PATH / "skbio_stratified_ngs_alignment_grid_search_j_igl"
res_df = aggregate_grid_search_results(results_dir, PARAMS, top_n, ground_truth_df, with_rev_comp=False)
res_path = f"results/prefiltering_grid_search_top_{top_n}_no_trash_alignments_fixed_diagonal_stratified_ngs_j_igl.csv"
res_df.to_csv(res_path)
res_df.sort_values("match_percent", ascending=False).head(20)

100%|██████████| 315/315 [01:00<00:00,  5.22it/s]

     top  kmer_size  distance_threshold  modulo  match_percent
251    5          5                   5       1       0.999816
242    5          5                   3       1       0.999816
161    5          5                   7       2       0.999770
231    5          5                   7       1       0.999770
141    5          5                   5       2       0.999770
238    5          5                   3       2       0.999770
156    5          5                   9       2       0.999725
266    5          5                  11       2       0.999725
50     5          5                   9       1       0.999725
243    5          7                  15       1       0.999656
160    5          7                  17       1       0.999656
189    5          7                  13       1       0.999656
44     5          7                   9       1       0.999656
80     5          7                  11       1       0.999656
82     5          7                   7       1       0.999656
173    5          7                  19       1       0.999656
131    5          7                   5       1       0.999656
249    5          7                   3       1       0.999656
270    5          5                  13       2       0.999610
51     5          5                  15       2       0.999587

### IGK

In [12]:
results_dir = RESULTS_PATH / "skbio_stratified_ngs_alignment_grid_search_j_igk"
res_df = aggregate_grid_search_results(results_dir, PARAMS, top_n, ground_truth_df, with_rev_comp=False)
res_path = f"results/prefiltering_grid_search_top_{top_n}_no_trash_alignments_fixed_diagonal_stratified_ngs_j_igk.csv"
res_df.to_csv(res_path)
res_df.sort_values("match_percent", ascending=False).head(20)

100%|██████████| 315/315 [01:27<00:00,  3.59it/s]

     top  kmer_size  distance_threshold  modulo  match_percent
251    5          5                   5       1       0.999290
242    5          5                   3       1       0.999275
231    5          5                   7       1       0.999219
50     5          5                   9       1       0.999119
6      5          5                  11       1       0.998991
20     5          5                  15       1       0.998878
54     5          5                  13       1       0.998764
229    5          5                  17       1       0.998721
163    5          5                  19       1       0.998593
238    5          5                   3       2       0.998395
141    5          5                   5       2       0.998395
161    5          5                   7       2       0.998338
51     5          5                  15       2       0.998281
156    5          5                   9       2       0.998238
24     5          3                   3       3       0.998196
266    5          5                  11       2       0.998082
270    5          5                  13       2       0.998054
215    5          5                  17       2       0.998025
261    5          5                  19       2       0.997940
278    5          3                   3       2       0.997599