# Prefiltering grid search - C genes

In [4]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [5]:
from utils import *
from pathlib import Path
import pandas as pd

In [6]:
RESULTS_PATH = Path("/home/bartosz/Documents/riot/results/")

In [7]:
ngs_skbio = pd.read_csv("data/skbio_stratified_ngs_alignment_c.csv", index_col=0)
print(f"Number of sequences with evalue more than 0.001: {ngs_skbio[ngs_skbio['e_value'] > 0.001].shape[0]} / {ngs_skbio.shape[0]}")
ngs_skbio = ngs_skbio[ngs_skbio["e_value"] < 0.1]
ground_truth_df = ngs_skbio[["target_id"]]

Number of sequences with evalue more than 0.001: 148384 / 451390

## Top 5 genes

In [8]:
top_n = 5
PARAMS = ["top", "kmer_size", "distance_threshold", "modulo"]

### IGH

In [10]:
results_dir = RESULTS_PATH / "skbio_stratified_ngs_alignment_grid_search_c_igh"
res_df = aggregate_grid_search_results(results_dir, PARAMS, top_n, ground_truth_df, with_rev_comp=False)
res_path = f"results/prefiltering_grid_search_top_{top_n}_no_trash_alignments_fixed_diagonal_stratified_ngs_c_igh.csv"
res_df.to_csv(res_path)
res_df.sort_values("match_percent", ascending=False).head(20)

100%|██████████| 315/315 [06:56<00:00,  1.32s/it]

     top  kmer_size  distance_threshold  modulo  match_percent
242    5          5                   3       1       0.992219
251    5          5                   5       1       0.990869
141    5          5                   5       2       0.990485
238    5          5                   3       2       0.989343
131    5          7                   5       1       0.986671
82     5          7                   7       1       0.984610
161    5          5                   7       2       0.984590
298    5          5                   7       3       0.984410
44     5          7                   9       1       0.984374
96     5          5                   7       4       0.983382
74     5          5                   9       4       0.982538
124    5          5                   9       3       0.981938
32     5          5                   3       4       0.981779
188    5          7                   3       4       0.981677
11     5          7                   5       4       0.981252
231    5          5                   7       1       0.980995
58     5          5                  11       3       0.980408
86     5          7                   7       4       0.979469
109    5          7                   9       4       0.979380
282    5          7                  11       4       0.979359

### IGL

In [13]:
results_dir = RESULTS_PATH / "skbio_stratified_ngs_alignment_grid_search_c_igl"
res_df = aggregate_grid_search_results(results_dir, PARAMS, top_n, ground_truth_df)
res_path = f"results/prefiltering_grid_search_top_{top_n}_no_trash_alignments_fixed_diagonal_stratified_ngs_c_igl.csv"
res_df.to_csv(res_path)
res_df.sort_values("match_percent", ascending=False).head(20)

100%|██████████| 315/315 [00:34<00:00,  9.21it/s]

     top  kmer_size  distance_threshold  modulo  match_percent
242    3          5                   3       1       0.999289
251    3          5                   5       1       0.999147
57     3          3                   3       1       0.998934
50     3          5                   9       1       0.998934
231    3          5                   7       1       0.998152
6      3          5                  11       1       0.998152
10     3          5                   5       5       0.997939
18     3          5                   3       5       0.997939
131    3          7                   5       1       0.997868
40     3          3                   3       4       0.997868
82     3          7                   7       1       0.997868
249    3          7                   3       1       0.997868
80     3          7                  11       1       0.997797
25     3          5                   9       5       0.997797
243    3          7                  15       1       0.997797
123    3          5                   7       5       0.997797
160    3          7                  17       1       0.997797
44     3          7                   9       1       0.997797
173    3          7                  19       1       0.997797
189    3          7                  13       1       0.997797

### IGK

In [14]:
results_dir = RESULTS_PATH / "skbio_stratified_ngs_alignment_grid_search_c_igk"
res_df = aggregate_grid_search_results(results_dir, PARAMS, top_n, ground_truth_df)
res_path = f"results/prefiltering_grid_search_top_{top_n}_no_trash_alignments_fixed_diagonal_stratified_ngs_c_igl.csv"
res_df.to_csv(res_path)
res_df.sort_values("match_percent", ascending=False).head(20)

100%|██████████| 315/315 [01:03<00:00,  4.95it/s]

     top  kmer_size  distance_threshold  modulo  match_percent
170    3          3                   5       1            1.0
49     3          3                   9       2            1.0
229    3          5                  17       1            1.0
111    3          3                   3       5            1.0
110    3          3                  15       3            1.0
231    3          5                   7       1            1.0
278    3          3                   3       2            1.0
40     3          3                   3       4            1.0
41     3          3                   9       3            1.0
105    3          3                  11       4            1.0
238    3          5                   3       2            1.0
242    3          5                   3       1            1.0
251    3          5                   5       1            1.0
273    3          3                  19       4            1.0
270    3          5                  13       2            1.0
50     3          5                   9       1            1.0
262    3          3                  13       4            1.0
51     3          5                  15       2            1.0
85     3          3                  13       5            1.0
252    3          3                  15       4            1.0